jwt:
  key: "qpdne62dnnjxnsvs45xsgjdknmxgbm902xs##bdhx23gdhs79892nsmxs72nxbdbd55dv3#kmkmxdkddknwyjnjnsjjsnjs"
  access-token-expiration: 3600000
  refresh-token-expiration: 864000000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clinicnewdb
    username: clinic
    password: 12345678
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # yoki "validate", "create", "create-drop"
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  messages:
    basename: error/error
    encoding: UTF-8

